name: Test shell and environment

on: push

jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-shell
        shell: bash
        run: |
          pwd
          echo "Shell before running script to set +e: \"$-\""
          .github/workflows/set-plus-e.sh
          echo "Shell after running script to set +e: \"$-\""

          echo "Shell before running script to set +e in a subshell: \"$-\""
          (.github/workflows/set-plus-e.sh)
          echo "Shell after running script to set +e in a subshell: \"$-\""

          echo "Running shell script to set+e && exit 1"
          .github/workflows/exit-one.sh
          REZ=$?
          echo "$REZ is exit value"
          set -x
          echo "Run exit-one.sh in a subshell"
          (.github/workflows/exit-one.sh)
          echo "Didn't exit"
